"""Add role field to users table

Revision ID: fa1c8077c76a
Revises: 11f7ac7b7382
Create Date: 2025-07-24 11:47:25.195627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1c8077c76a'
down_revision = '11f7ac7b7382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.alter_column('user_image_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('tag_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_image_tags_tag_name'), ['tag_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_image_tags_user_image_id'), ['user_image_id'], unique=False)

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_images_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_images_user_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_image_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_image_tags_user_image_id'))
        batch_op.drop_index(batch_op.f('ix_user_image_tags_tag_name'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('tag_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_image_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
